version: '2.1'

services:
    nexus:
        image: sonatype/nexus3:3.30.0
        restart: unless-stopped
        ports:
            - "8082:8081"
            - "8085:8085"
        volumes:
            - ./nexus-data:/nexus-data:Z
