---
- name: 'Include openvpn-base'
  include_role:
    name: openvpn-base

- name: Extract ovpn client zip into /etc/openvpn
  unarchive:
    src: /tmp/{{openvpn_client_name}}.zip
    dest: /etc/openvpn/

- name: Rename /etc/openvpn/client.ovpn to client.conf
  copy:
    remote_src: True
    src: "/etc/openvpn/{{openvpn_client_name}}.ovpn"
    dest: "/etc/openvpn/{{openvpn_client_name}}.conf"
  notify:
    - restart openvpn
    - restart openvpn_client
