---
- include_tasks: "{{ ansible_os_family }}.yml"

- name: "Deploy VPN keys from {{vpnkeys_dir}}/{{openvpn_client_name}}.zip"
  unarchive:
    src: "{{ vpnkeys_dir }}/{{openvpn_client_name}}.zip"
    dest: /etc/openvpn/

- name: Rename /etc/openvpn/client.ovpn to client.conf
  copy:
    remote_src: True
    src: "/etc/openvpn/{{openvpn_client_name}}.ovpn"
    dest: "/etc/openvpn/{{openvpn_client_name}}.conf"
  notify:
    - restart openvpn
    - restart openvpn_client
