#
# nexus3 repomanager behind nginx router
# Based on https://github.com/sonatype/docker-nexus3
#
- name: ensure data directory exists
  file:
    path: "{{ item }}"
    recurse: no
    state: directory
    owner: root
    group: docker
    # using 777 because nexus JVM uses different user TODO: fix JVM user and docker permissions issue
    mode: 0777
  with_items:
    - /nexus-repomanager/data

- name: deploy sonatype/docker-nexus3
  copy:
    src: files/docker-compose.yml
    dest: /nexus-repomanager
    owner: dev

- name: build & start nexus3 docker container
  shell: |
    docker-compose build
    docker-compose up -d
  args:
    chdir: /nexus-repomanager

- name: add nginx route
  copy:
    src: files/artifacts.conf
    dest: /etc/nginx/conf.d/artifacts.conf
    owner: dev

- name: restart nginx
  service: name=nginx state=restarted
