# based on https://github.com/kamon-io/docker-grafana-graphite
version: '2.1'
services:
  monitoring_hub:
    restart: unless-stopped
    build: .      # image: kamon/grafana_graphite
    container_name: monitoring_hub
    ports:
      - '80:80'   # use port 82 for grafana
      - '81:81'   # use port 81 for graphite
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
