---
- name: mkdir /etc/iptables/
  file:
    path: /etc/iptables/
    state: directory

- name: 'Iptables 22, 1194, tun0 accept'
  iptables_raw:
    name: 'openvpn ssh tun filter'
    backup: yes
    rules: |
      -A INPUT -p tcp -m multiport --dports 22 -j ACCEPT
      -A INPUT -p udp -m multiport --dports 1194 -j ACCEPT
      -A INPUT -i tun0 -j ACCEPT

- name: 'Iptables tun0 MASQUERADE'
  iptables_raw:
    name: 'tun MASQUERADE'
    backup: yes
    table: nat
    rules: |
      -A POSTROUTING -o tun0 -j MASQUERADE

- name: Set ip forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present
