version: '3.2'

services:
  postgresql:
    image: postgres:12.5
    restart: always
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nextcloud:
    image: nextcloud:20.0.1-apache
    restart: always
    ports:
      - 127.0.0.1:8088:80
    volumes:
      - ./nextcloud:/var/www/html
        # - ./config.php:/var/www/html/config/config.php
        #- /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - NEXTCLOUD_ADMIN_PASSWORD=adminOk332233
      - NEXTCLOUD_ADMIN_USER=nc
      - REDIS_HOST=redis
      # - REDIS_HOST_PORT (default: 6379) Optional port for Redis, only use for external Redis servers that run on non-standard ports.
      # - REDIS_HOST_PASSWORD (not set by default) Redis password
      - SMTP_HOST=email-smtp.eu-west-1.amazonaws.com
      - SMTP_SECURE=ssl
      - SMTP_PORT=465
      # (default: LOGIN): The method used for authentication. Use PLAIN if no authentication is required.
      - SMTP_AUTHTYPE=LOGIN
      - SMTP_NAME=AKIA4XPAKXYKA54UZL7P
      - SMTP_PASSWORD=BJT1gv19/vJzXPQxh2nlc0LjfjQKBsI0F39lEAfkxCbB
      - MAIL_FROM_ADDRESS=no-reply
      - MAIL_DOMAIN=autofaq.ai
    depends_on:
      - postgresql
      - redis

#  cron:
#    image: nextcloud:20.0.1-apache
#    restart: "unless-stopped"
#    volumes:
#      - ./nextcloud:/var/www/html
#    entrypoint: /cron.sh
#    depends_on:
#      - postgresql
#      - redis


  redis:
    image: redis:5.0.5
    restart: "unless-stopped"
    volumes:
      - ./redis/data:/data:z
