- name: deploy dockprom
  copy:
    src: files/dockprom
    dest: /opt/
    owner: dev

- name: start containers
  shell: docker-compose up -d
  args:
    chdir: /opt/dockprom

# TODO fixme better way
- name: KLUDGE fix write permissions
  shell: chmod -R ag+rwx grafana_data prometheus_data
  args:
    chdir: /opt/dockprom
    warn: false
