- name: "Add user {{ user }} ({{comment}})"
  user:
    name: "{{ user }}"
    state: present
    shell: /bin/bash
    groups: sudo,docker
    comment: "{{ comment }}"

- name: "Update pub keys of {{user}}"
  authorized_key:
    user: "{{ user }}"
    key: "{{ key }}"
