---
- name: Make sure we have the 'dev' group
  become: yes
  group:
    name: dev
    state: present

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add dev user
  user:
    name: dev
    state: present
    shell: /bin/bash
    groups: sudo,docker,dev
    comment: "Developer common passwordless user"

- name: Allow 'dev' to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%dev'
    line: '%dev ALL=(ALL) NOPASSWD: ALL'

- name: Add users
  vars:
    user: "{{ item }}"
    pubkey: "{{ lookup('file', '{{item.key}}') }}"
  include: configure_user.yml
  with_items:
   - { name: "den",       key: "reefactor.keys",    groups: "sudo,docker",  comment: "admin user" }
   - { name: "devops",    key: "devops.keys",       groups: "sudo,docker",  comment: "admin user" }
   - { name: "lab",       key: "lab.keys",          groups: "docker",       comment: "can run docker" }
   - { name: "localuser", key: "empty.keys",        groups: "",    comment: "without pubkey ssh access" }

- name: Delete users
  user:
    name: "{{ item.name }}"
    state: absent
    remove: yes
  with_items:
  - { name: "exmember" }

- name: Authorize admin users to impersonate as dev
  authorized_key:
    user: "dev"
    exclusive: True
    key: "{{
      lookup('file', 'reefactor.keys') + '\n' +
      lookup('file', 'devops.keys')
    }}"
