- name: Install docker package
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: install python-pip
  apt:
    name: python3-pip
    state: latest

- name: Install docker-compose
  # https://docs.docker.com/compose/install/#install-compose-on-linux-systems
  get_url:
    url : https://github.com/docker/compose/releases/download/{{version}}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,a+x'
  vars:
    - version: "1.29.1"

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user docker group
  user:
    name: dev
    group: docker
    append: yes

# As we can configure the docker daemon via the configuration
# file `/etc/docker/daemon.json` here we take the opportunity
# of placing one of our own at the relevant destination.
# TODO upgrade to docker v18. and add "compress": "true" to daemon.json log-opts
- name: Prepare default daemon configuration
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  register: docker_daemon_json_installed

- name: Restart docker with new daemon.json defaults
  service:
    name: docker
    state: restarted
  when: docker_daemon_json_installed.changed

- name: Autostart docker service after reboot
  service:
    name: docker
    enabled: true
