---
- name: Add docker repo key
  apt_key:
    id: "{{ docker_repo_signature }}"
    keyserver: "{{ docker_repo_url }}"
    state: present

- name: Ensure https transport for apt
  apt:
    name: apt-transport-https
    state: present

- name: Add docker repo
  apt_repository:
    repo: "{{ docker_repo }}"
    mode: '644'
    update_cache: yes

- name: Install docker CE
  apt:
    name: "{{ docker_package }}"
    state: present

- name: Upgrade docker-py and docker-compose with pip
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
    - { name: docker, version: "3.7.0" }
    - { name: docker-compose, version: "1.23.2" }

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user docker group
  user:
    name: "{{ docker_user }}"
    group: docker
    append: yes