- name: base
  hosts: all
  become: true
  tasks:
    - name: Ensure https transport for apt
      apt:
        name: apt-transport-https
        state: present
    - name: install python-pip
      apt:
        name: python3-pip
        state: latest
