- hosts: openvpn-server
  become: yes
  tasks:
    - name: 'Fetch zip archive with client credentials from openvpn-server host'
      fetch:
        src: "/etc/openvpn/ovpns/{{item.name}}.zip"
        dest: ../vpnkeys/
        flat: yes
      with_items: "{{ openvpn_clients_active }}"

- hosts: openvpn_clients_group
  become: yes
  roles:
    - role: openvpn-client
